services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pinto-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=mysql://root:12345@mysql:3306/pinto
    depends_on:
      - mysql
    restart: unless-stopped
  mysql:
    image: mysql:8.0
    container_name: mysql-pinto
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_0900_ai_ci
      - --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: pinto
    ports:
      - "3306:3306"
    volumes:
      - mysql_pinto_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
  adminer:
    image: adminer
    container_name: adminer-pinto
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysql
volumes:
  mysql_pinto_data:
