name: Deploy to Cloud Run

on:
  push:
    branches: [main]
  workflow_dispatch: # 수동 배포도 가능하게

env:
  PROJECT_ID: cellular-client-470408-j4
  SERVICE_NAME: pinto-app
  REGION: us-central1

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Enable Corepack & pin pnpm
        run: |
          corepack enable
          corepack prepare pnpm@9.12.3 --activate
          pnpm -v

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Generate Prisma Client
        run: pnpm prisma:generate

      - name: Build Next.js app
        env:
          NEXT_STRICT: false
          NEXT_TELEMETRY_DISABLED: 1
        run: pnpm build

      # Google Cloud 인증
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ env.PROJECT_ID }}

      - name: Configure Docker to use gcloud
        run: gcloud auth configure-docker

      # Docker 이미지 빌드 및 푸시
      - name: Build and Push Docker image
        run: |
          docker build -f Dockerfile.simple -t gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA .
          docker push gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA

      # Cloud Run에 배포
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy $SERVICE_NAME \
            --image gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA \
            --region $REGION \
            --platform managed \
            --allow-unauthenticated \
            --port 3000 \
            --memory 2Gi \
            --cpu 2 \
            --max-instances 10 \
            --set-cloudsql-instances ${{ secrets.CLOUD_SQL_CONNECTION_NAME }} \
            --set-env-vars "NODE_ENV=production,NEXT_STRICT=false" \
            --set-env-vars "DATABASE_URL=${{ secrets.DATABASE_URL }}" \
            --set-env-vars "NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }}" \
            --set-env-vars "NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }}" \
            --quiet

      - name: Show deployment URL
        run: |
          echo "🚀 Deployment successful!"
          gcloud run services describe $SERVICE_NAME --region=$REGION --format='value(status.url)'